"""fine feature has been added

Revision ID: 162c8bed819d
Revises: 3879d3615d33
Create Date: 2025-08-16 00:26:59.646699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162c8bed819d'
down_revision = '3879d3615d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fine_date', sa.DateTime(), nullable=False),
    sa.Column('criminal', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('fine_amount', sa.Float(), nullable=False),
    sa.Column('total_fine', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fine')
    # ### end Alembic commands ###
