"""Blank Web For New Monitor

Revision ID: 1bfd26ccfed5
Revises: 162c8bed819d
Create Date: 2025-08-16 13:54:45.904320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfd26ccfed5'
down_revision = '162c8bed819d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cleaning_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])

    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fine_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_item_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])

    with op.batch_alter_table('meal_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_meal_record_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_member_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notice_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notice_monitor_id'))
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_member_monitor_id'))
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('meal_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meal_record_monitor_id'))
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_item_monitor_id'))
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fine_monitor_id'))
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('cleaning', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cleaning_monitor_id'))
        batch_op.drop_column('monitor_id')

    # ### end Alembic commands ###
