"""meal_count float

Revision ID: 357960386c2a
Revises: aaa3a004f0ed
Create Date: 2026-04-20 22:33:45.434189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357960386c2a'
down_revision = 'aaa3a004f0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_record', schema=None) as batch_op:
        batch_op.alter_column('meal_count',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_record', schema=None) as batch_op:
        batch_op.alter_column('meal_count',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
