"""Add role to Member and photo to Monitor

Revision ID: 3879d3615d33
Revises: 35c9364d9102
Create Date: 2025-08-02 00:48:34.639529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3879d3615d33'
down_revision = '35c9364d9102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
