"""empty message

Revision ID: aaa3a004f0ed
Revises: b3d8f521c09b
Create Date: 2025-08-20 13:52:32.881004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa3a004f0ed'
down_revision = 'b3d8f521c09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleaning_monitor_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fine_monitor_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('gas_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_monitor_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('meal_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_record_monitor_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_monitor_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('monitor_id')

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notice_monitor_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('monitor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_notice_monitor_id'), ['monitor_id'], unique=False)

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_member_monitor_id'), ['monitor_id'], unique=False)

    with op.batch_alter_table('meal_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_meal_record_monitor_id'), ['monitor_id'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_item_monitor_id'), ['monitor_id'], unique=False)

    with op.batch_alter_table('gas_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])

    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_fine_monitor_id'), ['monitor_id'], unique=False)

    with op.batch_alter_table('cleaning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'monitor', ['monitor_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_cleaning_monitor_id'), ['monitor_id'], unique=False)

    # ### end Alembic commands ###
