"""saved amount record added

Revision ID: b3d8f521c09b
Revises: 7115a209b2bf
Create Date: 2025-08-20 00:41:48.280493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d8f521c09b'
down_revision = '7115a209b2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_amount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('meal_amount', sa.Float(), nullable=True),
    sa.Column('gas_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_amount')
    # ### end Alembic commands ###
